// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: hands/hands.proto

package hands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suits int32

const (
	Suits_SUITS_ANY     Suits = 0
	Suits_SUITS_SPADE   Suits = 1
	Suits_SUITS_HEART   Suits = 2
	Suits_SUITS_CLUB    Suits = 3
	Suits_SUITS_DIAMOND Suits = 4
)

// Enum value maps for Suits.
var (
	Suits_name = map[int32]string{
		0: "SUITS_ANY",
		1: "SUITS_SPADE",
		2: "SUITS_HEART",
		3: "SUITS_CLUB",
		4: "SUITS_DIAMOND",
	}
	Suits_value = map[string]int32{
		"SUITS_ANY":     0,
		"SUITS_SPADE":   1,
		"SUITS_HEART":   2,
		"SUITS_CLUB":    3,
		"SUITS_DIAMOND": 4,
	}
)

func (x Suits) Enum() *Suits {
	p := new(Suits)
	*p = x
	return p
}

func (x Suits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suits) Descriptor() protoreflect.EnumDescriptor {
	return file_hands_hands_proto_enumTypes[0].Descriptor()
}

func (Suits) Type() protoreflect.EnumType {
	return &file_hands_hands_proto_enumTypes[0]
}

func (x Suits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suits.Descriptor instead.
func (Suits) EnumDescriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{0}
}

type DealRandomCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealRandomCardRequest) Reset() {
	*x = DealRandomCardRequest{}
	mi := &file_hands_hands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealRandomCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealRandomCardRequest) ProtoMessage() {}

func (x *DealRandomCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealRandomCardRequest.ProtoReflect.Descriptor instead.
func (*DealRandomCardRequest) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{0}
}

type DealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          uint64                 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealRequest) Reset() {
	*x = DealRequest{}
	mi := &file_hands_hands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealRequest) ProtoMessage() {}

func (x *DealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealRequest.ProtoReflect.Descriptor instead.
func (*DealRequest) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{1}
}

func (x *DealRequest) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          Suits                  `protobuf:"varint,1,opt,name=suit,proto3,enum=Suits" json:"suit,omitempty"`
	Rank          uint32                 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_hands_hands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetSuit() Suits {
	if x != nil {
		return x.Suit
	}
	return Suits_SUITS_ANY
}

func (x *Card) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type Hands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hands) Reset() {
	*x = Hands{}
	mi := &file_hands_hands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hands) ProtoMessage() {}

func (x *Hands) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hands.ProtoReflect.Descriptor instead.
func (*Hands) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{3}
}

func (x *Hands) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_hands_hands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{4}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_hands_hands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_hands_hands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{6}
}

func (x *AddUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_hands_hands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_hands_hands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_hands_hands_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_hands_hands_proto protoreflect.FileDescriptor

var file_hands_hands_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0b,
	0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x22,
	0x36, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x04, 0x73, 0x75, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x53, 0x75, 0x69, 0x74, 0x73, 0x52, 0x04, 0x73,
	0x75, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x24, 0x0a, 0x05, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x12, 0x1b, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x12, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x30, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x2b, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0x28, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x5b, 0x0a, 0x05, 0x53, 0x75,
	0x69, 0x74, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x49, 0x54, 0x53, 0x5f, 0x41, 0x4e, 0x59,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x55, 0x49, 0x54, 0x53, 0x5f, 0x53, 0x50, 0x41, 0x44,
	0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x55, 0x49, 0x54, 0x53, 0x5f, 0x48, 0x45, 0x41,
	0x52, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x49, 0x54, 0x53, 0x5f, 0x43, 0x4c,
	0x55, 0x42, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x55, 0x49, 0x54, 0x53, 0x5f, 0x44, 0x49,
	0x41, 0x4d, 0x4f, 0x4e, 0x44, 0x10, 0x04, 0x32, 0x5e, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x6c, 0x65,
	0x72, 0x12, 0x21, 0x0a, 0x08, 0x44, 0x65, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0c, 0x2e,
	0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x05, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0e, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x05,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x22, 0x00, 0x32, 0x68, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0f, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x36, 0x6f, 0x2f, 0x6e, 0x6f, 0x70, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_hands_hands_proto_rawDescOnce sync.Once
	file_hands_hands_proto_rawDescData []byte
)

func file_hands_hands_proto_rawDescGZIP() []byte {
	file_hands_hands_proto_rawDescOnce.Do(func() {
		file_hands_hands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hands_hands_proto_rawDesc), len(file_hands_hands_proto_rawDesc)))
	})
	return file_hands_hands_proto_rawDescData
}

var file_hands_hands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hands_hands_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hands_hands_proto_goTypes = []any{
	(Suits)(0),                    // 0: Suits
	(*DealRandomCardRequest)(nil), // 1: DealRandomCardRequest
	(*DealRequest)(nil),           // 2: DealRequest
	(*Card)(nil),                  // 3: Card
	(*Hands)(nil),                 // 4: Hands
	(*ListUsersRequest)(nil),      // 5: ListUsersRequest
	(*ListUsersResponse)(nil),     // 6: ListUsersResponse
	(*AddUserRequest)(nil),        // 7: AddUserRequest
	(*User)(nil),                  // 8: User
}
var file_hands_hands_proto_depIdxs = []int32{
	0, // 0: Card.suit:type_name -> Suits
	3, // 1: Hands.cards:type_name -> Card
	8, // 2: ListUsersResponse.users:type_name -> User
	8, // 3: AddUserRequest.user:type_name -> User
	2, // 4: Dealer.DealCard:input_type -> DealRequest
	1, // 5: Dealer.DealRandomCard:input_type -> DealRandomCardRequest
	7, // 6: GameManager.AddUser:input_type -> AddUserRequest
	5, // 7: GameManager.ListUsers:input_type -> ListUsersRequest
	3, // 8: Dealer.DealCard:output_type -> Card
	3, // 9: Dealer.DealRandomCard:output_type -> Card
	8, // 10: GameManager.AddUser:output_type -> User
	6, // 11: GameManager.ListUsers:output_type -> ListUsersResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hands_hands_proto_init() }
func file_hands_hands_proto_init() {
	if File_hands_hands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hands_hands_proto_rawDesc), len(file_hands_hands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hands_hands_proto_goTypes,
		DependencyIndexes: file_hands_hands_proto_depIdxs,
		EnumInfos:         file_hands_hands_proto_enumTypes,
		MessageInfos:      file_hands_hands_proto_msgTypes,
	}.Build()
	File_hands_hands_proto = out.File
	file_hands_hands_proto_goTypes = nil
	file_hands_hands_proto_depIdxs = nil
}
